In [1]:
%matplotlib inline
import pandas as pd
import seaborn as sns

In [2]:
cast = pd.read_csv("C:/Data Science/cast.csv")
print(cast.head())

                  title  year      name   type                character     n
0        Closet Monster  2015  Buffy #1  actor                  Buffy 4   NaN
1       Suuri illusioni  1985    Homo $  actor                   Guests  22.0
2   Battle of the Sexes  2017   $hutter  actor          Bobby Riggs Fan  10.0
3  Secret in Their Eyes  2015   $hutter  actor          2002 Dodger Fan   NaN
4            Steve Jobs  2015   $hutter  actor  1988 Opera House Patron   NaN

###  1) How many movies are listed in the titles dataframe?

In [3]:
print("Movies are listed in the titles dataframe :",cast['title'].count())

Movies are listed in the titles dataframe : 3611212

### 2) What are the earliest two films listed in the titles dataframe?

In [4]:
print("The earliest two films listed in the the titles dataframe:\n",cast['title'].head(2))

The earliest two films listed in the the titles dataframe:
 0     Closet Monster
1    Suuri illusioni
Name: title, dtype: object

### 3) How many movies have the title "Hamlet"?

In [5]:
Hamlet = cast[cast['title'] == "Hamlet"]
print("Total number of movies have the title name Hamlet :",Hamlet['title'].count())

Total number of movies have the title name Hamlet : 313

### 4) How many movies are titled "North by Northwest"?

In [6]:
North_by_Northwest = cast[cast['title'] == "North by Northwest"]
print("Total number of movies have the title name North by Northwest  :",North_by_Northwest['title'].count())

Total number of movies have the title name North by Northwest  : 112

### 5) When was the first movie titled "Hamlet" made?

In [7]:
print("The first movie titled Hamlet made in year :",Hamlet['year'].min())

The first movie titled Hamlet made in year : 1910

### 6) List all of the "Treasure Island" movies from earliest to most recent.

In [36]:
Treasure_Island = cast[cast['title'] == "Treasure Island"]
Treasure_Island.sort_values(by = 'year',ascending = True).reset_index()

,index,title,year,name,type,character,n
0,830114,Treasure Island,1918,Charles Gorman,actor,Prologue Player,NaN
1,840745,Treasure Island,1918,Joe Grant,actor,Undetermined child role,NaN
2,909157,Treasure Island,1918,Edwin Harley,actor,Prologue Player,NaN
3,3298306,Treasure Island,1918,Violet Radcliffe,actress,Long John Silver,3.0
4,1715014,Treasure Island,1918,Lloyd Perl,actor,Black Dog,4.0
...,...,...,...,...,...,...,...
185,2420089,Treasure Island,1999,Caveh Zahedi,actor,Harold,9.0
186,1637661,Treasure Island,1999,Nick Offerman,actor,Samuel,2.0
187,1375015,Treasure Island,1999,J.P. Manoux,actor,Officer Hughes,18.0
188,1797264,Treasure Island,1999,Victor Raider-Wexler,actor,Samowitz,10.0
189,307749,Treasure Island,1999,Bob Byington,actor,Thomas,12.0

### 7) How many movies were made in the year 1950?

In [9]:
movies_made_in_1950 = cast[cast['year'] == 1950]
print("Total movies were made in the year 1950 : ",len(movies_made_in_1950))

Total movies were made in the year 1950 :  22006

### 8) How many movies were made in the year 1960?

In [10]:
movies_made_in_1960 = cast[cast['year'] == 1960]
print("Total movies were made in the year 1960 : ",len(movies_made_in_1960))

Total movies were made in the year 1960 :  18456

### 9) How many movies were made from 1950 through 1959?

In [11]:
movies_1950s = cast[(cast['year'] >= 1950) & (cast['year'] <= 1959)]
print("The number of movies made from 1950 through 1959 is:",len(movies_1950s))

The number of movies made from 1950 through 1959 is: 210986

### 10) In what years has a movie titled "Batman" been released?

In [40]:
Batman = cast[cast['title'] == "Batman"]
print("years has a movie titled Batman been released :",Batman['year'].unique())

years has a movie titled Batman been released : [1943 1989]

### 11) How many roles were there in the movie "Inception"?

In [13]:
inception = cast[cast['title'] == "Inception"]
print("Total no. roles were there in the movie Inception -",len(inception))

Total no. roles were there in the movie Inception - 77

### 12) How many roles in the movie "Inception" are NOT ranked by an "n" value?

In [14]:
print("The number of roles in the movie Inception are NOT ranked by an n value :",inception['n'].isnull().sum())

The number of roles in the movie Inception are NOT ranked by an n value : 26

### 13) But how many roles in the movie "Inception" did receive an "n" value?

In [15]:
print("The number of roles in the movie Inception are NOT ranked by an n value :",inception['n'].notnull().sum())

The number of roles in the movie Inception are NOT ranked by an n value : 51

### 14) Display the cast of "North by Northwest" in their correct "n"-value order, ignoring roles that did not earn a numeric "n" value.

In [16]:
North_by_Northwest1 = cast[(cast['title'] == "North by Northwest") & cast['n'].notnull()]
North_by_Northwest1.sort_values(by ='n',ascending = True)

,title,year,name,type,character,n
840374,North by Northwest,1959,Cary Grant,actor,Roger O. Thornhill,1.0
3361396,North by Northwest,1959,Eva Marie Saint,actress,Eve Kendall,2.0
1404704,North by Northwest,1959,James Mason,actor,Phillip Vandamm,3.0
3024085,North by Northwest,1959,Jessie Royce Landis,actress,Clara Thornhill,4.0
343701,North by Northwest,1959,Leo G. Carroll,actor,The Professor,5.0
2923056,North by Northwest,1959,Josephine Hutchinson,actress,Mrs. Townsend,6.0
1634552,North by Northwest,1959,Philip Ober,actor,Lester Townsend,7.0
1229083,North by Northwest,1959,Martin Landau,actor,Leonard,8.0
2357939,North by Northwest,1959,Adam Williams,actor,Valerian,9.0
1746383,North by Northwest,1959,Edward Platt,actor,Victor Larrabee,10.0
642085,North by Northwest,1959,Robert Ellenstein,actor,Licht,11.0
2212083,North by Northwest,1959,Les Tremayne,actor,Auctioneer,12.0
447893,North by Northwest,1959,Philip Coolidge,actor,Dr. Cross,13.0
1454363,North by Northwest,1959,Patrick McVey,actor,Sergeant Flamm,14.0
198496,North by Northwest,1959,Edward Binns,actor,Captain Junket,15.0
1334726,North by Northwest,1959,Ken Lynch,actor,Charley - Chicago Policeman,16.0

### 15) Display the entire cast, in "n"-order, of the 1972 film "Sleuth".

In [43]:
Sleuth = cast[(cast['title'] == 'Sleuth') & (cast['year'] == 1972)& cast['n'].notnull()]
a = Sleuth.sort_values(by = 'n',ascending=False)
print(a.head(1))

          title  year          name   type               character    n
1396572  Sleuth  1972  Teddy Martin  actor  Police Constable Higgs  6.0

### 16) Now display the entire cast, in "n"-order, of the 2007 version of "Sleuth".

In [44]:
Sleuth1 = cast[(cast['title'] == 'Sleuth') & (cast['year'] == 2007) & cast['n'].notnull()]
Sleuth1.sort_values(by = 'n',ascending=False).head(1)

          title  year           name   type    character    n
1741124  Sleuth  2007  Harold Pinter  actor  Man on T.V.  3.0

### 17) How many roles were credited in the silent 1921 version of Hamlet?

In [19]:
Silent = cast[(cast['title'] == 'Hamlet') & (cast['year'] == 1921)]
print("The total number of roles were credited in the silent 1921 version of Hamlet :",len(Silent))

The total number of roles were credited in the silent 1921 version of Hamlet : 9

### 18) How many roles were credited in Branagh’s 1996 Hamlet?

In [20]:
Branagh = cast[(cast['title'] == 'Hamlet') & (cast['year'] == 1996) ]
print("The total no. of roles were credited in Branagh’s 1996 Hamlet:",len(Branagh))

The total no. of roles were credited in Branagh’s 1996 Hamlet: 54

### 19) How many "Hamlet" roles have been listed in all film credits through history?

In [21]:
Hamlet_roles = cast[cast['title'] == 'Hamlet'].sort_values(by = 'n')
print("The total no. of Hamlet roles have been listed in all film credits through history:",len(Hamlet_roles))

The total no. of Hamlet roles have been listed in all film credits through history: 313

### 20) How many people have played an "Ophelia"?

In [50]:
Ophelia = cast[(cast['character'] == 'Ophelia')]
people_played = len(Ophelia)
print("The total people have played an Ophelia :",people_played)

The total people have played an Ophelia : 111

### 21) How many people have played a role called "The Dude"?

In [23]:
The_Dude = cast[cast['title'] == 'The Dude']
role_played = The_Dude['n'].isnull().sum()
print("The total no. of people have played a role called The Dude:",role_played)

The total no. of people have played a role called The Dude: 0

### 22) How many people have played a role called "The Stranger"?

In [52]:
The_Stranger = cast[cast['title'] == 'The Stranger'] 
print("The total no. of people have played a role called The Stranger:",The_Stranger)

The total no. of people have played a role called The Stranger:                 title  year                 name     type  \
10330    The Stranger  1995            Ash Adams    actor
75036    The Stranger  1987    Adolfo Aristarain    actor
78623    The Stranger  1987        Jacques Arndt    actor
223678   The Stranger  1946           David Bond    actor
273212   The Stranger  1995    Andre Rosey Brown    actor
...               ...   ...                  ...      ...
3535868  The Stranger  1987       Sof?a Viruboff  actress
3561361  The Stranger  1946     Martha Wentworth  actress
3573827  The Stranger  1995  Sandra Lee Williams  actress
3598206  The Stranger  1946        Loretta Young  actress
3602620  The Stranger  1987     Patricia Zangaro  actress

                     character     n
10330       Deputy Steve Stowe   5.0
75036               Movie goer   NaN
78623                     Rhea   7.0
223678                 Student   NaN
273212              Tony Brown  18.0
...                        ...   ...
3535868              Desk Girl  26.0
3561361                   Sara   9.0
3573827                Darlene  17.0
3598206        Mary Longstreet   2.0
3602620  Female Police Officer  16.0

[106 rows x 6 columns]

### 23) How many roles has Sidney Poitier played throughout his career?

In [25]:
Sidney_Ploitier = cast[cast['name']  == 'Sidney Poitier'].sort_values(by = 'name').count()
print("The total no. of roles has Sidney Poitier played throughout his career:",Sidney_Ploitier.iloc[5])

The total no. of roles has Sidney Poitier played throughout his career: 42

### 24) How many roles has Judi Dench played?

In [26]:
Judi_Dench= cast[cast['name']  == 'Judi Dench'].count()
print("The total no. of roles has Judi Dench played:",Judi_Dench['name'])

The total no. of roles has Judi Dench played: 55

### 25) List the supporting roles (having n=2) played by Cary Grant in the 1940s, in order by year.

In [27]:
Cary_Grant_Played_roles = cast[(cast['name'] == 'Cary Grant') & ((cast['year'] >= 1940) & (cast['year'] <= 1949)) & (cast['n'] == 2) ]
print("List of the supporting roles (having n=2) played by Cary Grant in the 1940s in order by year:",Cary_Grant_Played_roles)

List of the supporting roles (having n=2) played by Cary Grant in the 1940s in order by year:                    title  year        name   type    character    n
840371  My Favorite Wife  1940  Cary Grant  actor         Nick  2.0
840381    Penny Serenade  1941  Cary Grant  actor  Roger Adams  2.0

### 26) How many roles were available for actors in the 1950s?

In [28]:
actors_1950s = cast[(cast['type'] == 'actor') & ((cast['year'] >= 1950) & (cast['year'] <= 1959))].sort_values(by = 'n').notnull().sum()
print("Total no. of roles were available for actors in the 1950s -",actors_1950s.iloc[5])

Total no. of roles were available for actors in the 1950s - 80890

### 27) How many roles were available for actresses in the 1950s?

In [29]:
actresses_1950s = cast[(cast['type'] == 'actress') & ((cast['year'] >= 1950) & (cast['year'] <= 1959))].sort_values(by = 'n').notnull().sum()
print("Total no. of roles were available for actresses in the 1950s -",actresses_1950s.iloc[5])

Total no. of roles were available for actresses in the 1950s - 34986

### 28) How many leading roles (n=1) were available from the beginning of film history through 1980?

In [30]:
leading_roles_available = cast[(cast['n'] == 1) & (cast['year'] == 1980)].count()
print("Total no. of leading roles (n=1) were available from the beginning of film history through 1980 -",leading_roles_available.iloc[5])

Total no. of leading roles (n=1) were available from the beginning of film history through 1980 - 1143

### 29) How many non-leading roles were available through from the beginning of film history through 1980?

In [31]:
leading_roles_available = cast[(cast['year'] == 1980)].isnull().sum()
print("Total no. of leading roles (n=1) were available from the beginning of film history through 1980 -",leading_roles_available.iloc[5])

Total no. of leading roles (n=1) were available from the beginning of film history through 1980 - 4227

### 30) How many roles through 1980 were minor enough that they did not warrant a numeric "n" rank?

In [32]:
minor = cast[cast['year'] == 1980].isnull().sum()
print("Total no. roles through 1980 were minor enough that they did not warrant a numeric n rank -",minor.iloc[5])

Total no. roles through 1980 were minor enough that they did not warrant a numeric n rank - 4227